[toolchain]
anchor_version = "0.31.1"

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_auction_program = "816xF6MFwtfBvqAJhsgbB67tgJ515jS7Ts8tbKfZ9QYw" # From declare_id! in lib.rs

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet" # Default, can be changed to Devnet, Mainnet-beta, etc.
wallet = "~/.config/solana/id.json" # Default wallet path

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" # Default test script